# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory2)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: OctopusPack@4
  inputs:
    PackageId: 'GradesNew'
    PackageFormat: 'Zip'
    PackageVersion: '$(Build.BuildNumber)'
    OutputPath: '$(Build.ArtifactStagingDirectory2)'

- task: OctopusPush@4
  inputs:
    OctoConnectedServiceName: 'OctopusCloudOps'
    Space: 'Spaces-23'
    Package: '$(Build.ArtifactStagingDirectory2)/GradesNew.$(Build.BuildNumber).zip'
    Replace: 'false'

- task: OctopusCreateRelease@4
  inputs:
    OctoConnectedServiceName: 'OctopusCloudOps'
    Space: 'Spaces-23'
    ProjectGroup: 'ProjectGroups-42'
    ProjectName: 'Projects-181'