name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Push a package to Octopus Deploy
      uses: OctopusDeploy/push-package-action@v1.1.1
      with:
        space: "PaulC"
        api_key: ${{ secrets.OCTOPUSSERVERAPIKEY }}
        packages: "indexes.1.0.zip"
        server: ${{ secrets.OCTOPUSSERVERURL }}